---
title: "Automatisoitu skripti"
author: "Henrik Wejberg"
date: "2023-03-10"
output: html_document
---

```{r}
library(readxl)
library(pxweb)
library(tidyverse)
library(writexl)
library(jsonlite)

# Luetaan kaikkien maakuntien data. Kansantalouden aluetilinpito on 32
# POHJOIS-KARJALA ON 17
# Koko maa ja maakunnat on 1, 7:24
# : 1, 3:4, 6:8, 10:13, 15:19, 21:22, 24:28, 30:38
d <- pxweb_interactive()

# Kokeillaan tallentaa json file
url <- d$url

# Maakunnan voi vaihtaa kohdasta "Alue" ja "values": ["MK17"]
json_string <- '{
  "query": [
    {
      "code": "Alue",
      "selection": {
        "filter": "item",
        "values": ["MK12"]
      }
    },
    {
      "code": "Taloustoimi",
      "selection": {
        "filter": "item",
        "values": ["P1R"]
      }
    },
    {
      "code": "Toimiala",
      "selection": {
        "filter": "item",
        "values": ["SSS", "A01", "A02_A03", "B", "C10TC12", "C13TC15", "C16", "C17_C18", "C19TC22", "C23", "C24_C25", "C26_C27", "C28", "C29_C30", "C31TC33", "D_E", "F", "G", "H", "I", "J", "K", "L681_L68209_L683", "L68201_L68202", "M", "N", "O", "P", "Q", "R_S", "T"]
      }
    },
    {
      "code": "Sektori",
      "selection": {
        "filter": "item",
        "values": ["S1"]
      }
    },
    {
      "code": "Vuosi",
      "selection": {
        "filter": "item",
        "values": ["2020"]
      }
    },
    {
      "code": "Tiedot",
      "selection": {
        "filter": "item",
        "values": ["CP"]
      }
    }
  ],
  "response": {
    "format": "json"
  }
}'

px_data <- pxweb_get(url, query = json_string)

pyöritys <- as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")

# Poistetaan ensimmäisenä turhat sarakkeet 4 ja 5, sillä ne ovat vakioita koko aineistossa
pyöritys_pienempi <- pyöritys[,-c(4:5)]
data2 <- pyöritys_pienempi[-1,4]




# Muutetaan sarakkeen nimi toimivaksi, levennetään maakunnat sarakkeisiin ja poistetaan NA havainnot.
pyöritys_oikeassa_muodossa <- rename(pyöritys_pienempi, Käypiin_hintoihin = "Käypiin hintoihin, miljoonaa euroa") |>
  replace_na(list(Käypiin_hintoihin = 0)) 

# Tässä vaihtoehdossa voidaan filtteröidä Alueen mukaan, jolloin tuloksena jää 4 sarakkeen ja x rivin data, jossa numeraaliset arvot on allekkain
pyöritys_oikeassa_muodossa |> 
  pivot_wider(names_from = Alue, values_from = Käypiin_hintoihin)

# Toinen vaihtoehto on laittaa kaikki alueet sarakkeiksi ensin. Tällä tyylillä data2 excelissä on. Tässä muodossa on helppo valita numeraalisesti select funktion kautta halutut sarakkeet. Esim:
testi <- pyöritys_oikeassa_muodossa |> 
  pivot_wider(names_from = Alue, values_from = Käypiin_hintoihin) |>
  select(1:3, 5) |> 
  pivot_wider(names_from = c("Taloustoimi"), values_from = c("KOKO MAA", "MK02 Varsinais-Suomi"))
  

testi[,12] / testi[,3] 

# Tavoite on tässä saada jaettua Koko maalla kyseisen maa-/seutukunnan vastaavat arvot
pyöritys_oikeassa_muodossa |> 
  pivot_wider(names_from = Alue, values_from = Käypiin_hintoihin) |>
  select(1:3, 5) |>
  mutate(suhteellinen_osuus = )


# Data on oikeassa muodossa

data2 <- read_excel(lukuTiedosto,sheet='TTmaakunta',range="B3:P35")

# Valitaan Jussin skriptiin samanlaisella tavalla data 
pyöritys_oikeassa_muodossa |> select(1:4) |> pivot_wider(names_from = Taloustoimi, values_from = c("KOKO MAA", "MK01 Uusimaa"))

```





```{r}

# Määritellään lukutiedosto datalle
lukuTiedosto = "data/Alue_PT.xlsx"
# Luetaan data 
data1 <- read_excel(lukuTiedosto,sheet='PT2020'    ,range="B3:CC83")

# Tehdään 64 lukujono tulevia laskuja varten
nInd0 = 64

# Tehdään aputaulu, joka on 64x64 matriisi, jonka arvoina on välituotekäyttö panos-tuotostaulukosta
aputaulu = as.matrix(data1[(1:nInd0), 1+(1:nInd0)]);


IOmat0 = matrix(0, nrow = nInd0, ncol = nInd0)
for(i in 1:nInd0){  for(j in 1:nInd0) IOmat0[i,j] = as.numeric(aputaulu[i,j]);  }


y0      = matrix(0, nrow = nInd0, ncol = 1    );
GVA0    = matrix(0, nrow = 1,     ncol = nInd0);
output0 = matrix(0, nrow = 1,     ncol = nInd0);
labor0  = matrix(0, nrow = 1,     ncol = nInd0);
for(i in 1:nInd0){ y0[i,1]      = as.numeric( data1[i,  ncol(data1)-1] )     ;  }
for(j in 1:nInd0){ GVA0[1,j]    = as.numeric( data1[76, 1+j          ] )     ;  }
for(j in 1:nInd0){ output0[1,j] = as.numeric( data1[77, 1+j          ] )     ;  }
for(j in 1:nInd0){ labor0[1,j]  = as.numeric( data1[80, 1+j          ] )*1000;  }


# "aluetilinpito" aggregation key (last value is "nrow+1")
aggKey = c(1,2,4,5,6,7,8,10,14,15,17,19,20,22,24,27,28,31,36,37,41,44,46,51,55,56,57,59,64,65)


nInd = (length(aggKey)-1);
IOmat  = matrix(0, nrow=nInd, ncol=nInd)
y      = matrix(0, nrow=nInd, ncol=1)
GVA    = matrix(0, nrow=1,    ncol=nInd)
output = matrix(0, nrow=1,    ncol=nInd)
labor  = matrix(0, nrow=1,    ncol=nInd)
for (i in 1:nInd ){
  for (j in 1:nInd ){
    IOmat[i,j] = sum(IOmat0[aggKey[i]:(aggKey[i+1]-1),aggKey[j]:(aggKey[j+1]-1)])
  }
  y[i,1]      = sum( y0     [aggKey[i]:(aggKey[i+1]-1), 1                         ] )
  GVA[1,i]    = sum( GVA0   [1,                         aggKey[i]:(aggKey[i+1]-1) ] )
  output[1,i] = sum( output0[1,                         aggKey[i]:(aggKey[i+1]-1) ] )
  labor[1,i]  = sum( labor0 [1,                         aggKey[i]:(aggKey[i+1]-1) ] )
}
IOmat
sum(IOmat0)-sum(IOmat)
y
GVA
output
labor


Amat = matrix(0, nrow = nInd, ncol = nInd);
for (i in 1:nInd ) Amat[i,] = IOmat[i,]/output
Amat

vaMult    = GVA/output
laborMult = labor/output

vaMult
laborMult

#####################################################################################
#####################################################################################
#
# regional account(s)
#

dim(data2)
regnInd0 = 30;

regoutput0 = matrix(0, nrow=1,    ncol=regnInd0);
regoutput  = matrix(0, nrow=1,    ncol=nInd  );

regoutput0 <- t(data2) 

# aggrgoidaan kiinteistötoimialat
regaggKey = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31)


for (i in 1:nInd ){
  regoutput[1,i] = sum( regoutput0[1, regaggKey[i]:(regaggKey[i+1]-1) ] )
}
regoutput

tot_regoutput = sum(regoutput)
tot_output    = sum(output)

# location quotients: simple, cross-industry, ...
SLQ  = matrix( 0, nrow=nInd, ncol=nInd )
CILQ = matrix( 0, nrow=nInd, ncol=nInd )

for (i in 1:nInd ){
  for (j in 1:nInd ){
    SLQ[i,j]  = ( regoutput[i] / output[i] )/( tot_regoutput / tot_output );
    CILQ[i,j] = ( regoutput[i] / output[i] )/(  regoutput[j] / output[j]  );
  }
}

SLQ
CILQ

write_xlsx(list(as.data.frame(IOmat), as.data.frame(Amat), as.data.frame(SLQ), as.data.frame(CILQ)),"testi.xlsx")




```



```{r}
# Tehdään SLQ:sta tekniset kertoimet alueelle

TC <- ifelse(SLQ > 1, 1, SLQ)

result <- Amat * TC




n = nrow(Amat)
# Identity matrix
Imat = diag(n)
# Vector of ones
onevec = matrix(1,n,1)
indvec = matrix(0,n,1)
indvec[indIndex] = 1
# Ty?voiman tarve = ty?panoskerroin x tuotos
Laborvec = laborMult * output
# Arvonlis?ys = arvonlis?yskerroin x tuotos
Vvec     =    vaMult * output

# Leontief inverse
Linv = solve(Imat-Amat)

# basic model test - should be zeros!
Linv %*% y - t(output)


##  Final use based IO-modeling ##

# Final use analysis matrix
XF = Linv %*% diag(as.vector(y))
XF

diag(as.vector(vaMult))    %*% XF
diag(as.vector(laborMult)) %*% XF


```